---
output:
  md_document:
    variant: gfm
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## DESCRIPCION:


Este curso utiliza la teoría de la probabilidad en espacios discretos y continuos, así como el cálculo diferencial e integral, para comprender los fundamentos matemáticos de la inferencia estadística clásica: estimación de parámetros y contraste de hipótesis, y desarrollar las herramientas de estadística contemporánea para sus aplicaciones en diversas áreas. 

**Profesor:** Shu Wei Chou Chen (shuwei.chou@ucr.ac.cr)

## Presentaciones

| Tema                        |  Clases                               | Laboratorio 
|-----------------------------|---------------------------------------|-------------------------------
| 1. Introducción             |       [Clase01](Clase_01.html)   |       
|                             |       [Clase02](Clase_02.html)   |   
|                             |       [Clase03](Clase_03.html)   | [Lab Tema 1](./lab01.html)      
| 2. Estimación Puntual       |       [Clase04](Clase_04.html)   |  
|                             |       [Clase05](Clase_05.html)   |      
|                             |       [Clase06](Clase_06.html)   |       
|                             |       [Clase07](Clase_07.html)   |      
|                             |       [Clase08](Clase_08.html)   | [Lab Tema 2](./lab02.html)  
| 3. Estimación por intervalo |       [Clase09](Clase_09.html)   |  
|                             |       [Clase10](Clase_10.html)   | 
|                             |       [Clase11](Clase_11.html)   | [Lab Tema 3](./lab03.html)  
| 4. Contraste de hipótesis   |       [Clase12](Clase_12.html)   |  
|                             |       [Clase13](Clase_13.html)   | 
|                             |       [Clase14](Clase_14.html)   | [Lab Tema 4a](lab04a.html)
|                             |       [Clase15](Clase_15.html)   | [Lab Tema 4b](lab04b.html)  
| 5. Estad. no paramétrica    |       [Clase16](Clase_16.html)   |  
|                             |       [Clase17](Clase_17.html)   | [Lab Tema 5](./lab05a.html)  

